### ISSUE TITLE
Error build when using -DWITH_INT_SINK 

### ISSUE THREAD

**Issue by baekguihyun** [opencord/fabric-tofino#1]
Hello, Developer.

I tried to build fabric-tofino with -DWITH_INT_SINK option, but occurrence Error at P4 source.

```
$ make build PROFILES=fabric-int
rm -rf src/main/resources/p4c-out
*** Compiling profile 'fabric-int' for mavericks_sde_9_0_0 platform...
*** Output in /home/forwiz/fabric-tofino/tmp/fabric-int/mavericks_sde_9_0_0
make: *** [fabric-int] Error 3
```

**Environment**
- OS: Ubuntu 18.04
- ONOS's Version: 2.2.2
- BF-SDE version: 9.0.0 (with BSP)
- Docker version: 19.03.8, build afacb8b7f0

**To Reproduce**
1. [Makefile](https://github.com/opencord/fabric-tofino/blob/33a6cc43ecf15353beb6eb4070f1e1cbfb9ffe6f/Makefile)
  - Line 34:
    ```
    fabric-int:
        @${p4-build} fabric-int "-DWITH_INT_SOURCE -DWITH_INT_TRANSIT -DWITH_INT_SINK"
    ```
  - Line 40: 
    ```
    fabric-spgw-int:
        @${p4-build} fabric-spgw-int "-DWITH_SPGW -DWITH_INT_SOURCE -DWITH_INT_TRANSIT -DWITH_INT_SINK"
    ```

**Comment by ccascone** [comment]
Hi @baekguihyun , unfortunately, support for the INT sink functionality for Tofino is not complete. You should be able to compile with full INT support for BMv2, but not for Tofino. The errors you see are expected.

Also, beware that your legal agreement with Barefoot/Intel might not allow sharing the output of products as the compiler on public channels like this one.

**Comment by baekguihyun** [comment]
Thanks for your answer.
