### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by hrezae2** [opencord/fabric-tofino#3]
I am getting the following error when I run make build PROFILES=all

warning: Ignoring egress extract of @not_extracted_in_egress header: hdr.packet_out
warning: Ignoring egress extract of @not_extracted_in_egress header: hdr.packet_out
Internal compiler error. Please submit a bug report with your code

I am using SDE 9.7.0 and I think it's because I am using this SDE version which is newer than 9.0.0 which is mentioned in the tutorial. Can anyone help me with a solution rather than downgrading to SDE 9.0.0? Thanks!

**Comment by ccascone** [comment]
Answered in #2
